services:
  gateway:
    build: ./gateway
    dockerfile: Dockerfile
    ports:
      - "8080:8080"

  worker:
    build: ./worker
    dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials

  playground:
    build: ./playground
    dockerfile: Dockerfile
    ports:
      - "8501:8501"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"