name: Worker Workflow
run-name: Deploy Worker
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  quickstart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "success"